In [41]:
import pandas as pd
import numpy as np

In [42]:
lst =[1,2,3,4,5]

pd.Series(lst)

0    1
1    2
2    3
3    4
4    5
dtype: int64

## giving index from our own end

In [43]:
pd.Series(data = lst , index = [1,2,3,4, 5])

1    1
2    2
3    3
4    4
5    5
dtype: int64

## Series through dictionary values

In [44]:
steps ={'day1': 4000 , "day2": 5000}
pd.Series(steps)

day1    4000
day2    5000
dtype: int64

## Using repeat functions

In [45]:
pd.Series(5).repeat(3)

0    5
0    5
0    5
dtype: int64

## AGGREGATE FUNCTIONS

In [46]:

sr = pd.Series([1,2,3,4,5,6])
sr.agg(["max", "min"])

max    6
min    1
dtype: int64

## APPENDING FUNCTIONS

In [47]:
sr1 = pd.Series([1,-2,3])
sr2 = pd.Series([1,2,3])
pd.concat([sr1,sr2])

0    1
1   -2
2    3
0    1
1    2
2    3
dtype: int64

## string functions

Upper and Lower Function
 
 Len function
 
 Strip Function
 
 Split Function
 
 Contains Function
 
 Replace Function
 
 Count Function
 
 Startswith and Endswith Function
 
 Find Finction

In [48]:

ser = pd.Series(["Eshant Das" , "Data Science" , "Geeks for Geeks" , 'Hello World' , 'Machine Learning'])
ser.str.upper()

0          ESHANT DAS
1        DATA SCIENCE
2     GEEKS FOR GEEKS
3         HELLO WORLD
4    MACHINE LEARNING
dtype: object

In [49]:

ser = pd.Series(["Eshant Das" , "Data Science" , "Geeks for Geeks" , 'Hello World' , 'Machine Learning'])
ser.str.lower()

0          eshant das
1        data science
2     geeks for geeks
3         hello world
4    machine learning
dtype: object

## Creating a data frame

In [51]:
lst = ['Geeks', 'For', 'Geeks', 'is', 'portal', 'for', 'Geeks']
pd.DataFrame(lst)

        0
0   Geeks
1     For
2   Geeks
3      is
4  portal
5     for
6   Geeks

## column selection

In [56]:
data = { "Name":  ["Aayush" , "Kartik", "Shivam", "Keshav"],
        "Qualification": ["Btech", "Bsc", "Bams", "bcom"],
        "Age": [22,23,24,25],
        "Address": ["Agra", "Jaipur","Shimla","Bangalore"]}
df = pd.DataFrame(data)
df

     Name Qualification  Age    Address
0  Aayush         Btech   22       Agra
1  Kartik           Bsc   23     Jaipur
2  Shivam          Bams   24     Shimla
3  Keshav          bcom   25  Bangalore

In [58]:
df[["Name", "Age"]]

     Name  Age
0  Aayush   22
1  Kartik   23
2  Shivam   24
3  Keshav   25