In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('Data.csv')
data

   Country   Age   Salary Purchased
0   France  44.0  72000.0       Yes
1    Spain  27.0  48000.0       Yes
2      NaN  30.0  54000.0       NaN
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [3]:
int(data['Salary'].mean())

63777

In [4]:
data['Salary'] = data['Salary'].fillna(data['Salary'].mean()).astype('int')
data['Salary']

0    72000
1    48000
2    54000
3    61000
4    63777
5    58000
6    52000
7    79000
8    83000
9    67000
Name: Salary, dtype: int32

In [5]:
data['Age'] = data['Age'].fillna(data['Age'].mean()).astype('int')

In [6]:
data['Age']

0    44
1    27
2    30
3    38
4    40
5    35
6    38
7    48
8    50
9    37
Name: Age, dtype: int32

In [7]:
data

   Country  Age  Salary Purchased
0   France   44   72000       Yes
1    Spain   27   48000       Yes
2      NaN   30   54000       NaN
3    Spain   38   61000        No
4  Germany   40   63777       Yes
5   France   35   58000       Yes
6    Spain   38   52000        No
7   France   48   79000       Yes
8  Germany   50   83000        No
9   France   37   67000       Yes

## simple imputer

In [8]:
from sklearn.impute import SimpleImputer

In [9]:
df = pd.read_csv('Data.csv')

In [10]:
imputer = SimpleImputer(missing_values=np.nan ,strategy='mean')

imputer.fit(df[['Salary' ,'Age']])

SimpleImputer()

In [11]:
df[['Salary' , 'Age']] = imputer.transform(df[['Salary' ,'Age']])

In [12]:
df['Salary'] =df['Salary'].astype('int')

In [13]:
df['Age'] =df['Age'].astype('int')

In [14]:
df

   Country  Age  Salary Purchased
0   France   44   72000       Yes
1    Spain   27   48000       Yes
2      NaN   30   54000       NaN
3    Spain   38   61000        No
4  Germany   40   63777       Yes
5   France   35   58000       Yes
6    Spain   38   52000        No
7   France   48   79000       Yes
8  Germany   50   83000        No
9   France   37   67000       Yes

In [15]:
df1 = pd.read_csv('Data.csv')

In [16]:
imputer = SimpleImputer(strategy='most_frequent')

df1 = pd.DataFrame(
    imputer.fit_transform(df1),
    columns=df1.columns
)

In [17]:
df1

   Country   Age   Salary Purchased
0   France  44.0  72000.0       Yes
1    Spain  27.0  48000.0       Yes
2   France  30.0  54000.0       Yes
3    Spain  38.0  61000.0        No
4  Germany  40.0  48000.0       Yes
5   France  35.0  58000.0       Yes
6    Spain  27.0  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes